### ISSUE TITLE
Selecting apps

### ISSUE THREAD

**Issue by tchx84** [klausenbusk/flathub-stats#1]
Hey Kristian,

This is pretty cool! Have you considered using a better widget for selecting the app-id ?

e.g.
```
<datalist id="apps">
    <option value="com.github.tchx84.Flatseal">
    <option value="org.sugarlabs.Pippy">
    ...
</datalist>
<input type="text" list="apps" />
```

**Comment by klausenbusk** [comment]
Hi @tchx84, thanks for the feedback! `<input>` + `<datalist>` does indeed provide a better user experience.

Feel free to open a new issue or comment on this issue, if you have more feedback :)

**Comment by tchx84** [comment]
> Hi @tchx84, thanks for the feedback! `<input>` + `<datalist>` does indeed provide a better user experience.
> 
> Feel free to open a new issue or comment on this issue, if you have more feedback :)

I just did :) Thanks!
