### ISSUE TITLE
Why stats does not working?

### ISSUE THREAD

**Issue by vikdevelop** [klausenbusk/flathub-stats#19]
Hello, it seems that the stats are not working, because the last stats are from 26.11.2022, 4 days old. Previously, the stats were at most 2 days old, so why is it not working now?

**Comment by klausenbusk** [comment]
Hi, there was a few failed workflow runs due to transient network errors, which caused this, ex: https://github.com/klausenbusk/flathub-stats/actions/runs/3561041586.
