### ISSUE TITLE
Other basic stats

### ISSUE THREAD

**Issue by tchx84** [klausenbusk/flathub-stats#2]
From a developer POV, it would be helpful to see basic stats, per-app, like:

* Total downloads.
* Average downloads per-day.

Having a global overall would be nice enough, but even better if it's filtered by the current selected time window.

**Comment by klausenbusk** [comment]
Something like this?

**Comment by tchx84** [comment]
> Something like this?

Exactly like this, thanks! This information is invaluable.

**Comment by klausenbusk** [comment]
I just added "download type filtering" as the old way of showing data, could be a bit misleading.
