### ISSUE TITLE
Average results seems odd

### ISSUE THREAD

**Issue by tchx84** [klausenbusk/flathub-stats#4]
![image](https://user-images.githubusercontent.com/481418/86272245-3ebbaa80-bb9c-11ea-937b-b42e0bd072de.png)

For the 14 days time window, it says:
* Total: 1008
* Average: 42

But, 1008 / 14 = 72

Possible issues:
a. the total is wrog.
b. the average is not really the average (median?)
c. is dividing by the wrong amount of days (maybe mixing between archs?)

**Comment by klausenbusk** [comment]
Good catch! :)

>  c. is dividing by the wrong amount of days (maybe mixing between archs?)

That seems to be the case.

**Comment by klausenbusk** [comment]
This should be fixed now. It required 3 commits as I was a bit too fast :)
