### ISSUE TITLE
Allow defining package name in url

### ISSUE THREAD

**Issue by pktiuk** [klausenbusk/flathub-stats#7]
It would be great if your site would allow defining showed package from URL level.

It would make sharing statistic of app easier.

**Comment by klausenbusk** [comment]
Good idea! I will look into it soonish! :)

**Comment by pktiuk** [comment]
It would be good to also define other parameters like showing installs/updates/both and period of time. :D

**Comment by klausenbusk** [comment]
> It would be good to also define other parameters like showing installs/updates/both and period of time. :D

Yeh that is the idea. Store all configurable parameter as a ["hash"](https://developer.mozilla.org/en-US/docs/Web/API/Location/hash).

**Comment by g-fb** [comment]
I created a [tampermonkey](https://www.tampermonkey.net) script to do this

`https://klausenbusk.github.io/flathub-stats/?id=com.georgefb.haruna&interval=14`

```
// ==UserScript==
// @name         Flathub Stats
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       https://github.com/g-fb/
// @match        https://klausenbusk.github.io/flathub-stats*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    const params = new URLSearchParams(window.location.search)
    const id = params.get('id');
    const interval = params.get('interval')

    let intervalSelectElement = document.getElementById("interval-select");
    let refElement = document.getElementById("ref");
    refElement.addEventListener("change", setFlatpakId);

    function setFlatpakId() {
        refElement.value = id;
        intervalSelectElement.value = interval;
        refElement.removeEventListener("change", setFlatpakId);
    }
})();
```

**Comment by klausenbusk** [comment]
This has been fixed. Please wait a few minutes for the change to be deployed.
